//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveComparerLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BandedSignalsVector")]
        public string AudioFileToVectorMode {
            get {
                return ((string)(this["AudioFileToVectorMode"]));
            }
            set {
                this["AudioFileToVectorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int StfftNumberOfFrames {
            get {
                return ((int)(this["StfftNumberOfFrames"]));
            }
            set {
                this["StfftNumberOfFrames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\WaveComparer\\XmlLibrary.Xml")]
        public string LibraryLocation {
            get {
                return ((string)(this["LibraryLocation"]));
            }
            set {
                this["LibraryLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.06,0.60")]
        public string FrequencyPartitions {
            get {
                return ((string)(this["FrequencyPartitions"]));
            }
            set {
                this["FrequencyPartitions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FrequencyLogarithmicScale {
            get {
                return ((bool)(this["FrequencyLogarithmicScale"]));
            }
            set {
                this["FrequencyLogarithmicScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\WaveComparer\\TrainingMeasure.Xml")]
        public string MeasureLocation {
            get {
                return ((string)(this["MeasureLocation"]));
            }
            set {
                this["MeasureLocation"] = value;
            }
        }
    }
}
